In [25]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier

original_path = "./data/ai4i2020.csv"
original = pd.read_csv(original_path)
original.describe()

,UDI,Air temperature [K],Process temperature [K],Rotational speed [rpm],Torque [Nm],Tool wear [min],Machine failure,TWF,HDF,PWF,OSF,RNF
count,10000.00000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.00000
mean,5000.50000,300.004930,310.005560,1538.776100,39.986910,107.951000,0.033900,0.004600,0.011500,0.009500,0.009800,0.00190
std,2886.89568,2.000259,1.483734,179.284096,9.968934,63.654147,0.180981,0.067671,0.106625,0.097009,0.098514,0.04355
min,1.00000,295.300000,305.700000,1168.000000,3.800000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000
25%,2500.75000,298.300000,308.800000,1423.000000,33.200000,53.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000
50%,5000.50000,300.100000,310.100000,1503.000000,40.100000,108.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000
75%,7500.25000,301.500000,311.100000,1612.000000,46.800000,162.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000
max,10000.00000,304.500000,313.800000,2886.000000,76.600000,253.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.00000

Remove unnecessary columns and one-hot-encode the "Type"-column before creating new CSVs to avoid doing it every time

In [26]:
original.drop(columns=["UDI", "Product ID", "TWF", "HDF", "PWF", "OSF", "RNF"], inplace=True)
original = pd.get_dummies(original, columns=["Type"])

In [27]:
production = original.sample(frac=0.2, random_state=22)
production.describe()

,Air temperature [K],Process temperature [K],Rotational speed [rpm],Torque [Nm],Tool wear [min],Machine failure
count,2000.000000,2000.000000,2000.000000,2000.000000,2000.000000,2000.000000
mean,300.008600,309.987850,1538.085500,39.844250,109.604500,0.035000
std,2.010273,1.490546,169.011809,9.787036,63.320683,0.183826
min,295.500000,306.000000,1168.000000,3.800000,0.000000,0.000000
25%,298.300000,308.800000,1428.000000,32.800000,56.000000,0.000000
50%,300.100000,310.100000,1510.000000,39.300000,110.000000,0.000000
75%,301.500000,311.025000,1617.000000,46.900000,164.000000,0.000000
max,304.500000,313.800000,2886.000000,71.800000,246.000000,1.000000

In [28]:
test_data = original.drop(production.index)
test_data.describe()

,Air temperature [K],Process temperature [K],Rotational speed [rpm],Torque [Nm],Tool wear [min],Machine failure
count,8000.000000,8000.000000,8000.000000,8000.000000,8000.000000,8000.000000
mean,300.004012,310.009987,1538.948750,40.022575,107.537625,0.033625
std,1.997872,1.482087,181.771202,10.014178,63.734479,0.180273
min,295.300000,305.700000,1181.000000,4.200000,0.000000,0.000000
25%,298.300000,308.800000,1422.000000,33.300000,52.000000,0.000000
50%,300.100000,310.100000,1501.000000,40.200000,108.000000,0.000000
75%,301.500000,311.100000,1611.000000,46.700000,162.000000,0.000000
max,304.400000,313.800000,2874.000000,76.600000,253.000000,1.000000

In [29]:
production.to_csv("./data/production_data.csv", index=False)
test_data.to_csv("./data/test_data.csv", index=False)

In [30]:
test_data.head()

,Air temperature [K],Process temperature [K],Rotational speed [rpm],Torque [Nm],Tool wear [min],Machine failure,Type_H,Type_L,Type_M
1,298.2,308.7,1408,46.3,3,0,False,True,False
3,298.2,308.6,1433,39.5,7,0,False,True,False
6,298.1,308.6,1558,42.4,14,0,False,True,False
7,298.1,308.6,1527,40.2,16,0,False,True,False
8,298.3,308.7,1667,28.6,18,0,False,False,True